### ISSUE TITLE
code running bug

### ISSUE THREAD

**Issue by leo31cm** [tschaefermedia/DataMining-I-TeamProject#1]
![image](https://user-images.githubusercontent.com/16796079/57141251-18448880-6dba-11e9-88cc-2104a3a0a6c6.png)

**Comment by leo31cm** [comment]
My solution

![image](https://user-images.githubusercontent.com/16796079/57180160-3081d980-6e86-11e9-8b22-cccfe0c1a72a.png)

**Comment by tschaefermedia** [comment]
Just update in here or create a pull request from your fork, I will overtake it
